project:
  type: website
  output-dir: docs

website:
  title: "Handbook of Statistics of Extremes"
  navbar:
    left:
      - href: index.qmd
        text: About
      - contents.qmd
      - data.qmd
      - suppinfo.qmd
      - edicont.qmd
      - links.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



